version: 2

sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - identifier: raw_gz_sales
         name: sales
       - identifier: raw_gz_product
         name: product
       - identifier: raw_gz_ship
         name: ship