version: 2

sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - identifier: raw_gz_sales #sales 
         name: sales
         description: Greenweez sales/ orders -> product -> kpi

         loaded_at_field: "CAST(date_date AS TIMESTAMP)"
         freshness: 
           warn_after:
             count: 90
             period: day
         
         columns:
          - name: pdt_id
            description: foreign key for products table
            tests:
              - not_null

          - name: orders_id
            description: foreign key for orders tables
            tests:
              - not_null

         tests:
           - unique:
              column_name: "(orders_id || '_' || pdt_id)"


       - identifier: raw_gz_product #product
         name: product
         description: Greenweez list of products and prices associated

         columns:
          - name: products_id
            description: primary key
            tests:
              - not_null
              - unique


       - identifier: raw_gz_ship #ship
         name: ship
         description: Greenweez list of orders with cost and fee associated to the shipping

         columns:
          - name: orders_id
            description: primary key
            tests:
              - not_null
              - unique
              
       - identifier: raw_gz_adwords # campaign adwords
         name: adwords
         description: Daily campaign detail of adwords
         
         columns:
          - name: date_date
            description: foreign key
            tests:
              - not_null

          - name: campaign_key
            description: foreign key
            tests:
              - not_null

         tests:
           - unique:
              column_name: "(date_date || '_' || campaign_key)"

       - identifier: raw_gz_criteo # campaign criteo
         name: criteo
         description: Daily campaign detail of criteo
         
         columns:
          - name: date_date
            description: foreign key
            tests:
              - not_null

          - name: campaign_key
            description: foreign key
            tests:
              - not_null

         tests:
           - unique:
              column_name: "(date_date || '_' || campaign_key)"

       - identifier: raw_gz_facebook # campaign facebook
         name: facebook
         description: Daily campaign detail of facebook
         
         columns:
          - name: date_date
            description: foreign key
            tests:
              - not_null

          - name: campaign_key
            description: foreign key
            tests:
              - not_null

         tests:
           - unique:
              column_name: "(date_date || '_' || campaign_key)"

       - identifier: raw_gz_bing # campaign bing
         name: bing
         description: Daily campaign detail of bing
         
         columns:
          - name: date_date
            description: foreign key
            tests:
              - not_null

          - name: campaign_key
            description: foreign key
            tests:
              - not_null

         tests:
           - unique:
              column_name: "(date_date || '_' || campaign_key)"

models:
  - name: int_order_margin
    description: Calculation of all the KPI needed on each orders
    columns:
      - name: orders_id
        description: order number as primary key
        tests:
          - not_null
          - unique

  - name: finance_days
    description: calculation of summed up KPI on daily report
    columns:
      - name: date_date
        description: market day as primary key
        tests:
          - not_null
          - unique
          
          
          